### ISSUE TITLE
Reports Filter -> March -> Error

### ISSUE THREAD

**Issue by Triggsy22** [download-monitor/download-monitor#497] opened 2018-04-09 11:18 UTC
Hello,

there is a bug in the Filter on the Reports Page in the Admin Menu.
If you choose March as a Filter and click apply, you got one of the following urls.
wp-admin/edit.php?post_type=dlm_download&page=download-monitor-reports&tab=totals&chart=line&period=day&date_from=**NaN-NaN-NaN**&date_to=NaN-NaN-NaN
wp-admin/edit.php?post_type=dlm_download&page=download-monitor-reports&tab=totals&chart=line&period=day&date_from=**NaN-NaN-NaN**&date_to=2018-4-8
wp-admin/edit.php?post_type=dlm_download&page=download-monitor-reports&tab=totals&chart=line&period=day&date_from=2018-2-8&date_to=**NaN-NaN-NaN**

So, everytime you use March, May, Octobre, December you got "NaN-NaN-NaN"
Every other Month are working very well.

Tested Browser: Chrome, Firefox. 
Also Tested on two different Servers.

Thanks.

**Comment by barrykooij** [comment] 2018-04-13 11:10
@Triggsy22 I can't reproduce this error. When I select March 1 to March 31, it works. I suspect that there is a plugin or theme conflict on your website. Could you please try if the error still occurs with only this plugin activated with a default WordPress theme (e.g. twentyfifteen). I understand this can be a bit of a hassle but it's the only way we can be sure it's a bug in this plugin.

**Comment by barrykooij** [comment] 2018-04-13 11:11
@Triggsy22 Also, do you happen to know what PHP version your servers are runnign?

**Comment by Triggsy22** [comment] 2018-04-13 12:24
I tested a few things.
If i change my Backend Language to English, everything works fine.
But if i change it back to German, the Error above appears again :)
So it has something todo with the AdminUserLanguage.

**Comment by barrykooij** [comment] 2018-04-13 12:25
@Triggsy22 Thanks so much for this information, this helps a lot! I'll debug some more and see if I can fix this!

**Comment by barrykooij** [comment] 2018-04-13 15:09
Fixed! Will be released in 4.0.7

**Closed** 2018-04-13 15:09 UTC
Labels: Bug, Unconfirmed
