### ISSUE TITLE
Logs not showing 

### ISSUE THREAD

**Issue by ranjith16** [download-monitor/download-monitor#271] opened 2015-04-27 07:47 UTC
Hi i am not able to view the logs since its not getting reflected in the log section.

Please do something and fix it as soon as possible.

The main motive of the plugin itself is to keep the logs. So please update as soon as you can.

**Comment by barrykooij** [comment] 2015-04-29 10:08
Confirmed. Duplicate of #270

**Closed by barrykooij** 2015-04-29 10:08 UTC
Labels: Bug, Duplicate
