### ISSUE TITLE
Download counter / logs are incorrect

### ISSUE THREAD

**Issue by zaro** [download-monitor/download-monitor#401] opened 2017-02-26 12:49 UTC
The  download counts is increasing count always, regardless of the HTTP method used.
This results in HEAD requests counted towards the number of downloads, while there was no download.

**Comment by barrykooij** [comment] 2017-02-28 12:16
I've dealt with something similar in the past. I agree this is not intended behavior but because we're rewriting a large portion of related code in `4.0` I'm assigning it to `4.0` milstone.

**Closed** 2017-11-01 13:52 UTC
Labels: Bug, Logs, Optimize
