### ISSUE TITLE
No access message being show to random users

### ISSUE THREAD

**Issue by iron-man** [download-monitor/download-monitor#289] opened 2015-05-29 03:44 UTC
All users coming to my site are automatically created as subscribers, so everyone is a member.  However, I am getting reports of random events where the user is shown the no access message for all downloads, no matter what brower or operating system they try it on.  In fact one of these instance is an admin for the site.  I've verified that they are logged in, but to no avail.  Please point in the right direction for troubleshooting this, or solving it.  As is, it seems completely random as to which user sees the no access message.

**Comment by barrykooij** [comment] 2015-06-16 09:24
Hey @iron-man,

Sorry for my late reply! Are you hosted on WPEngine or another host that caches aggressively? If so, could you email them and ask them not to cache anything in the /download/*/ structure? This resolved the issue for another customer on WPEngine who has the exact same problem!

Kind Regards,

Barry Kooij

**Comment by barrykooij** [comment] 2015-07-03 09:02
@iron-man any update on this?

**Comment by barrykooij** [comment] 2015-07-09 09:30
Closing because I can't reproduce this and reporter isn't responding. Feel free to reopen when this conflict persists.

**Closed by barrykooij** 2015-07-09 09:30 UTC
Labels: Bug, Unconfirmed
